title: Datarefs
email: is@ismaelsow.com
description: >- # this means to ignore newlines until "baseurl:"
  Datarefs is a free SQL course + reference that focuses on <strong>practice. If you read the short lessons and do the carefully paced practice problems, you'll get good at SQL pretty fast.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
